
services:
  backend:
    build: .
    container_name: ArtPortfolio_API
    restart: always
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - art_network
  

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - art_network
      
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - art_network
    
  caddy:
    image: caddy:latest
    container_name: ArtPortfolio_Caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
    networks:
      - art_network
      
volumes:
  mongo-data:
  redis-data:
  node_modules:

networks:
  art_network:
    driver: bridge
